# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-30 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('name', models.CharField(max_length=64, verbose_name='公司名称')),
                ('status', models.CharField(max_length=64, verbose_name='入库状态')),
                ('num', models.CharField(max_length=64, verbose_name='编码')),
            ],
        ),
    ]
