# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, null=True, unique=True)),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='用户密码')),
                ('email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('avatar', models.FileField(default='/avatars/default.png', upload_to='avatars/')),
            ],
        ),
    ]
